### ISSUE TITLE
Alignment of footer is disturbed, icons should be added for clearity

### ISSUE THREAD

**Issue by sohinirathor2004** [Mansi168/EmoWell#242]
There seem to be two problems with the footer. First, it's misaligned, so it doesn't look very polished. Second, it doesn't have any icons, so it's not immediately clear what all the different links do. Adding icons that correspond with the link text would help improve usability and make the site look more professional.

kindly look on it !!

**Comment by everly-gif** [comment]
Hi thanks for you suggestion. Please open issues in the suggested Issue templates, fill all the fields so that its easier to analyse issues. Secondly this issue isnt clear enough. Is the footer view misaligned in desktop or mobile? what is misaligned?, the columns ? the texts? Please re-open with better information
